### PR TITLE
[default-unit] Allow options to pass function transforms in

### PR DESCRIPTION
**Pull request by jkjustjoshing**
## Corresponding issue (if exists):
#1291 

## What would you like to add/fix?
Adds the ability to transform values when adding units to them.

## Todo

- [x] Add tests if possible
- [x] Add changelog if users should know about the change
- [x] Add documentation

### CODE REVIEW

**Comment by kof** [comment]
Well done!

**Comment by jkjustjoshing** [comment]
Anything I should be doing to fix the issue with Travis CI? Looks like it's an issue out of my hands.

**Comment by kof** [comment]
No it's just a permission thing, we found no way to allow external contributors to run their PR's through CI with browerstack

**Comment by kof** [comment]
released in 10.1.0

**Pull request merged**
