### PR TITLE
Added jss-expand package

### PR DESCRIPTION
**Pull request by HenriBeck**
There was an error while importing the package, which means we can't import the whole git history.

### CODE REVIEW

**Comment by kof** [comment]
I think this would be a good name for it jss-plugin-syntax-expand

**Comment by HenriBeck** [comment]
Renamed to jss-plugin-syntax-expand

**Comment by kof** [comment]
Unrelated: trying to run tests on master, it fails in many places, are there any steps one should do to run the tests? missing docs?

**Comment by HenriBeck** [comment]
Well yeah, some tests are failing because we moved out the function plugin and some tests inside the plugins actually depend on the function values.

**Comment by kof** [comment]
so how do we fix it? moving function values tests to the corresponding plugins?

**Comment by HenriBeck** [comment]
They will be fixed once we move the plugins to the monorepo and can set up the function plugin for the tests. I already did that for this plugin: jss-plugin-syntax-expand

**Comment by kof** [comment]
Alright, lets get through this, because we can't release anything right now

**Comment by kof** [comment]
sure and add a hint to the new repo

**Comment by kof** [comment]
wait, we need to migrate all links first

**Comment by kof** [comment]
and release a new version with migrated plugins

**Comment by kof** [comment]
a todo?

**Comment by HenriBeck** [comment]
which links to need to be migrated?

**Comment by kof** [comment]
everything that refers to the old repo, docs mostly

**Comment by HenriBeck** [comment]
Yeah, I think we can only update links when most of the repos are migrated because they contain links to other repos.

**Pull request merged**
