### PR TITLE
Add minification for SSR

### PR DESCRIPTION
**Pull request by perevezencev**
__Corresponding issue (if exists):__
#1021

### CODE REVIEW

**Comment by kof** [comment]
I wish you would have discussed this first, before investing time, because can't merge it like this.

1. This minification has cost that we have to measure
2. We will not increase bundle size like this
3. We need a clear use case presented. For e.g. would just removing whitespaces be sufficient for 90% of use cases?

**Comment by HenriBeck** [comment]
I think we can easily make this ourselves in the `toCSS` function by just not adding line breaks and removing the indentation.

**Comment by kof** [comment]
@HenriBeck yes, this is what original issue is about. The package he is using here, will do many more optimmizations, for e.g. converting to shorthands etc.

**Comment by perevezencev** [comment]
Yes, csso minify css completely, but this entails a number of degradations. 
I rewrote the bootstrap test to check how minification affects performance during runtime.
image
This result is not clear to me, I expected to see a decrease, so it is necessary to consider this in more detail.
The size of the package certainly increases, but `SheetsRegistry` is used only on the server, so it does not matter (correct me if I'm wrong).
As a summary, can add an option for complete minification and do basic minification (removing spaces) by default.

**Comment by kof** [comment]
> The size of the package certainly increases, but SheetsRegistry is used only on the server, so it does not matter (correct me if I'm wrong).

1. It is intended for SSR, but we don't know for sure how it is used, since it can be used at runtime as well.
2. We export it from index, so it will automatically get into the bundle. 
3. I think if you really want csso optimizations you will have to use it in your user code. This is not hard.

**Comment by kof** [comment]
> As a summary, can add an option for complete minification and do basic minification (removing spaces) by default.

Yes, I think this is what we can do in the core. The rest can be done outside. It's just calling `minify(extractedCSS)` and perfectly doable in userland.

**Comment by HenriBeck** [comment]
Closing this PR as this kind of optimization should be done in the user's code, and we can do a faster minification in our code.

**Comment by justsml** [comment]
Are the examples of this implemented in userland?

Can't seem to find it.

**Pull request closed without merging**
