### PR TITLE
Add SwissDev Jobs as a user

### PR DESCRIPTION
**Pull request by Vrq**
## Todo

- [x ] Add tests if possible
- [x ] Add changelog if users should know about the change
- [x ] Add documentation

### CODE REVIEW

**Comment by Vrq** [comment]
@kof would you mind having a look? :)

**Comment by Vrq** [comment]
@HenriBeck could you check it out, please? :)

**Comment by HenriBeck** [comment]
@Vrq how are you using `jss`? I can't find any style tag which would indicate the usage of `jss`

**Comment by Vrq** [comment]
@HenriBeck we started using it this year and the rollout in production is still ongoing but you can find it for example on: https://swissdevjobs.ch/open

**Comment by kof** [comment]
@Vrq I don't see jss on that site either, I looked into class names and looked into the header for generated style tags, but I am gonna just trust you on this and merge it.

**Comment by Vrq** [comment]
Thanks @kof! 
Maybe it's because of the caching, but it should be there:
code

**Pull request merged**
