### PR TITLE
Fix react peer dep version corresponding react-dom

### PR DESCRIPTION
**Pull request by behnammodi**
I changed `react` to `>=16.8.6` becuase `react-dom` is `16.8.6`

### CODE REVIEW

**Comment by kof** [comment]
thanks

**Comment by behnammodi** [comment]
@kof what is your opinion about convert class component to function component in `react-jss` package?

**Comment by kof** [comment]
you mean changing the underlying implementation of the HOC to use hooks inside?

**Comment by behnammodi** [comment]
@kof Yes exactly

**Comment by behnammodi** [comment]
Also `JssProvider`

**Comment by kof** [comment]
That's the plan, we have an issue for that somewhere. There is one thing that a class-based implementation does and hooks doesn't - merging classes when classes are passed to the HOC. We need to add this feature to the hooks interface first and then use it when migrating the HOC.

**Comment by kof** [comment]
Issue regarding merging the classes https://github.com/cssinjs/jss/issues/1276

**Comment by kof** [comment]
Couldn't find the issue for using hook inside of HOC, so created one  https://github.com/cssinjs/jss/issues/1505

**Comment by kof** [comment]
Here is a separate issue for mgirating the provider https://github.com/cssinjs/jss/issues/1506

**Comment by behnammodi** [comment]
Ok

**Comment by behnammodi** [comment]
Can I create a draft PR? and discuss on it

**Comment by kof** [comment]
sure

**Comment by kof** [comment]
released in https://github.com/cssinjs/jss/releases/tag/v10.7.0

**Pull request merged**
