### PR TITLE
Add class name escaping for the dev mode

### LINKED ISSUE #624: Classes does not work for Components with special chars in display name
@luiz290788 commented on [Mon Nov 13 2017](https://github.com/cssinjs/react-jss/issues/176)

The new prefix for the generated classes that use the display name of the decorated components are not being sanitized.

For example:
Decorated class display name "SomeOtherDecorator(Test)"
Generated classes ".SomeOtherDecorator(Test)-root-0-1"
The parenthesis in the classes is causing the problems here.

Suggested solution: Parse the display name of the component to remove the special characters.

---

@kof commented on [Mon Nov 13 2017](https://github.com/cssinjs/react-jss/issues/176#issuecomment-343913293)

Or escape the chars.

---

@luiz290788 commented on [Mon Nov 13 2017](https://github.com/cssinjs/react-jss/issues/176#issuecomment-343918731)

I was checking the code and thinking about the issue, it seems to be a jss issue instead of a react-jss issue. What do you think?

---

@kof commented on [Mon Nov 13 2017](https://github.com/cssinjs/react-jss/issues/176#issuecomment-343919101)

Well, ultimately yeah, as we are using property names in classes, they can also contain everything. We just never had that issue over there.

---

@kof commented on [Mon Nov 13 2017](https://github.com/cssinjs/react-jss/issues/176#issuecomment-343919693)

Also the escaping needs to be done in dev mode only, because in production we build short class names.

### PR DESCRIPTION
**Pull request by kof**
Fixes #624

### CODE REVIEW

**Comment by kof** [comment]
cc @oliviertassinari

**Comment by oliviertassinari** [comment]
I'm assuming you have noticed the implementation we use on Material-UI side:
https://github.com/callemall/material-ui/blob/f10ff11979ac085bb8e2dcd740c8f3e8c57becf8/src/styles/createGenerateClassName.js#L51
I haven't heard any issue limitation from our users so far. CSS escape support is not quite high:
capture d ecran 2017-11-13 a 15 06 54
It might be a pain for people to install this polyfill when developing/fixing bugs on less common browsers.

**Comment by kof** [comment]
This is a very outdated table!

**Comment by kof** [comment]
I saw the regex in mui. It is a half backed escaping. It is broken already.

**Comment by kof** [comment]
See a complete version https://github.com/mathiasbynens/CSS.escape

**Comment by kof** [comment]
Chrome, Firefox and Safari have support already, we can expect a polyfill installed.

**Comment by kof** [comment]
Actually I can add a warning in case it is missing!

**Comment by kof** [comment]
I would not do it, but we need it in dev mode only, so it is kinda ok, right?

**Comment by kof** [comment]
Also you don't know what user can put into the key name) it could be an emoji)

**Comment by oliviertassinari** [comment]
@kof I don't know the probabilities. What's the probability of one using a not supported CSS selection char vs one trying out his interface in dev in a browser requiring the polyfill? Either way, one will discover this limitation.

**Comment by kof** [comment]
Yes, but considered it is dev mode only, perf is not an issue, right?
In that case requiring polyfills is the standard way to go, right?

**Comment by kof** [comment]
I am adding a good warning, which explains whats wrong, so user will have an easy time.

**Comment by oliviertassinari** [comment]
perf is not an issue.

**Comment by oliviertassinari** [comment]
Yeap, the resolution story with the polyfill will be better.

**Comment by kof** [comment]
What happens actually if we write an invalid selector in a regular css file? The rule will be ignored, right?

**Comment by oliviertassinari** [comment]
> What happens actually if we write an invalid selector in a regular css file? The rule will be ignored, right?

The user won't see his style. He will have to dig deep to understand what's going one.

**Comment by kof** [comment]
Another option would be to just escape the component names on a different abstraction level and let user fix his escapings himself. Though as we are generating the class names and use rule keys sort of implicitly, it is probably a better DX to do what I do in this PR.

**Comment by kof** [comment]
If we leave it up to user, it is like saying: "Dude, don't touch class names, we will generate them for you" and then "Dude, you need to make sure your property names are CSS conform."

**Comment by oliviertassinari** [comment]
@kof Hard choice. Either way, we need to take care of it. You solution sounds good to me.

**Comment by kof** [comment]
Just added a test where I use emoji as a key we got a new feature to tweet about haha!

**Pull request merged**
