### PR TITLE
Removed -syntax from plugin package names.

### PR DESCRIPTION
**Pull request by kof**
A merge of unpkg pr by @appsforartists + adding react-jss to jss-starter-kit + renaming all packages to be without -syntax suffix/prefix.

### CODE REVIEW

**Comment by kof** [comment]
Something is wrong on the CI, I don't see those errors locally

**Comment by appsforartists** [comment]
Does it make sense to remove `value-` too, if you're removing `-syntax`?

**Comment by kof** [comment]
You mean in jss-plugin-rule-value-function and jss-plugin-rule-value-observables? it was ment like css rule and css value function/observable. Better ideas?

**Comment by HenriBeck** [comment]
I don't think we should drop the `rule-value`

**Comment by kof** [comment]
I just have no other idea how to call them, just jss-plugin-functions & jss-plugin-observables?

**Comment by appsforartists** [comment]
You know your naming conventions better than I do.  😃 

I just saw you dropped the category for one set, and didn't know if you wanted to drop it from the others.

**Comment by kof** [comment]
Ah no its not a category, its literally what they do ...

**Comment by kof** [comment]
We started to prefix with -syntax like babel but then realized some have syntax + additional effects, so it wasn't consistent.

**Comment by HenriBeck** [comment]
I think we need to split this PR into three PRs:
- Rename packages (this has nothing to do with unpkg)
- Add unpkg support for the currently existing packages
- Add the jss-starter-kit package

This will make it easier to find out what is wrong with the tests

**Comment by appsforartists** [comment]
I believe the tests were passing here, modulo the missing `react-jss` bundle:

https://github.com/cssinjs/jss/pull/936

We could rebase in the `react-jss` fix, merge it, and then have this one just be the renaming of the packages.

**Comment by kof** [comment]
react-jss is added to starter kit and merged, will send a separate PR for renaming

**Pull request closed without merging**
