### PR TITLE
chore: add `es` build.

### PR DESCRIPTION
**Pull request by umidbekkarimov**
screen shot 2017-09-20 at 16 52 54

### CODE REVIEW

**Comment by kof** [comment]
Thanks for the PR!

Why do you need rollup for that?

**Comment by umidbekkarimov** [comment]
Webpack adds too much extra code.

That can be avoided with [ModuleConcatenationPlugin](https://webpack.js.org/plugins/module-concatenation-plugin/) but it works only with webpack@3 (and I'm not sure output will be smaller than rollup output).

Currently rollup is a winner in case of libs.

See also [good post](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) from rollup maintainer.

**Comment by kof** [comment]
I was actually experimenting with both, while rollup gives the immediate advantage, webpack is a better overall project to choose. Lets compare what would be the difference and if we can find a webpack plugin to do the best possible output.

**Comment by umidbekkarimov** [comment]
es: webpack@3 + 'ModuleConcatenationPlugin'
old/es: rollup

screen shot 2017-09-20 at 17 39 49

dist: webpack@3 
old/dist: webpack@2

screen shot 2017-09-20 at 17 39 55

**Comment by umidbekkarimov** [comment]
Webpack has it's own internal functionality and module system, thats what makes it great for apps, but not so good for libraries.

**Pull request closed without merging**
