### PR TITLE
remove nag message from postinstall script

### LINKED ISSUE #881: Please remove postinstall message about donating
While I understand the need to ask for donations, having it as the [postinstall message](https://github.com/cssinjs/jss/blob/master/packages/jss/package.json#L42), to me, isn't the most ideal location.

Downsides of having it there:
- It clutters up server logs (it does not respect the `--quiet` flag
- It is excessive (4 lines long)
- It sets a bad precedent/example. If every package did this, there would be hundreds of these messages.

This type of message is better suited to be at the top of the repo (hint hint), in the readme file and on the website.

### PR DESCRIPTION
**Pull request by slang800**
closes #881

I don't know what JSS is (it was installed as a dep of another dep in a project I'm maintaining), but this message shows up in the logs of my CI for every single run and it's getting annoying.

### CODE REVIEW

**Comment by kof** [comment]
The suggestion was to use https://github.com/cssinjs/jss/issues/881#issuecomment-428726121

**Comment by slang800** [comment]
I think my solution is far more elegant. It requires zero environment variables and zero additional deps :wink:

**Comment by kof** [comment]
Does it also has integrated reminder for the user to support software where some other people spend a lot of their private time on instead of spending time with their families?

**Comment by kof** [comment]
TBH I don't care about it, because it simply doesn't bring anything. A few contributors came probably not over this channel, so I am just going to merge it.

**Pull request merged**
