### PR TITLE
fix: react-jss/src/utils/sheets.js getSheetOptions use options.genera…

### PR DESCRIPTION
**Pull request by yeliex**
## Corresponding issue (if exists):
#1256 
## What would you like to add/fix?
react-jss/src/utils/sheets.js getSheetOptions use options.generateId first

## Todo

- [x] Add tests if possible
- [ ] Add changelog if users should know about the change
- [ ] Add documentation

### CODE REVIEW

**Comment by kof** [comment]
can you please add a test?

**Comment by yeliex** [comment]
@kof @HenriBeck Test added

I export getSheetOptions for testing the change only

**Comment by kof** [comment]
@yeliex thanks for doing it. The problem with this kind of tests - they don't tell us why it is testing it, it doesn't describe the use case. In addition, it tests internal implementation detail.

Tests should be written in the way the API is actually used by the user, so that on the long run we understand better why things work the way it work.

**Comment by yeliex** [comment]
@kof I have tried to write tests for exported APIs at first, but there have some troubles.

1. `createStyleSheet` is the main method of `sheet.js` and used by `createUseStyle` and `wthStyle`, so it is the best to write tests for it, but if want to do that, I have to create an instance for context and, because it depends on `context.managers`
2. `withStyles` and `createUseStyle` are two APIs which calls `createStyleSheet`, but they cannot get options with method return.

So, I just wrote tests for  `getSheetOptions `, and the tests make the edit in this PR as expected.

**Comment by kof** [comment]
How did you discover that bug, if I asked you to create a reproducible codesandbox example, how would you do it?

**Comment by NinoFocus** [comment]
example: https://codesandbox.io/s/boring-wood-s8uvg

**Comment by kof** [comment]
I would try to simply it and then, what do you expect to test, class names?

**Comment by yeliex** [comment]
> I would try to simply it and then, what do you expect to test, class names?

@kof  The rendered className of component `<Button size="large">Hello JSS</Button>` should be `ui-button ui-button-large` as output of `generateId` in `createUseOwnStyles`, but got `root-1-2-5 large-1-2-6`.

**Comment by kof** [comment]
right, so you want to test the generated css like this https://github.com/cssinjs/jss/blob/master/packages/react-jss/test-utils/createBasicTests.js#L49

**Comment by yeliex** [comment]
@kof @HenriBeck Test update, review please

cc @NinoFocus

**Comment by kof** [comment]
looks almost ready, we have shared tests between hoc and hooks here https://github.com/cssinjs/jss/blob/master/packages/react-jss/test-utils/createBasicTests.js

Probably not ideal location to have it in test-utils.

**Comment by yeliex** [comment]
> Probably not ideal location to have it in test-utils.
@kof What is the meaning of `Probably not ideal location`? Would you want me to transfer the test to test-utils?

**Comment by kof** [comment]
I ment that the fact you didn't find shared tests is probably because having test generator function in test-utils isn't a good idea. Right now your test should go there though, to be written once and used for both.

**Comment by yeliex** [comment]
@kof 
I found the test utils, actually.  And I did not do that because the way to create `styled component` is different for `hok` and `hooks` in these tests 
```
// Component for hoc
const withCustom = styles =>
        withStyles(styles, {
          generateId: rule => `ui-${rule.key}`
        })

      const StyledComponent = withCustom({
        button: {
          color: 'red'
        }
      })(props => <button className={props.classes.button} type="button" />)

// for hooks 
const useCustom = styles =>
        createUseStyles(styles, {
          generateId: rule => `ui-${rule.key}`
        })

      const useStyles = useCustom({
        button: {
          color: 'red'
        }
      })

      const StyledComponent = props => {
        const classes = useStyles(props)

        return <button className={classes.button} type="button" />
      }
```
It is different with the tests in `createBaseTests`, the core code to call `createUseStyles` and `withStyles`  are not reusable.

**Comment by kof** [comment]
it's possible, see https://github.com/cssinjs/jss/pull/1263/files  there is an options as second argument

Your commits are preserved in that PR, so I am gonna close this one and merge the other one, let's continue there

**Pull request closed without merging**
