### PR TITLE
[all] Fix peer deps

### PR DESCRIPTION
**Pull request by HenriBeck**
__What would you like to add/fix?__
Upgrades all of the peer dependencies to 10.0.0-alpha.8 and fixes the range of some of the peer dependencies

### CODE REVIEW

**Comment by kof** [comment]
damn, we need it to be automated, added a todo in #984

**Comment by HenriBeck** [comment]
We could easily automate them if we would use normal dependencies instead of peer + dev dependencies.

The reason why lerna doesn't automate it is that peer dependencies should be as wide as possibles.

**Comment by kof** [comment]
Then we might need a custom script or something....

**Comment by HenriBeck** [comment]
If we want to operate in "locked" mode, so have the same version across all packages when can use normal dependencies instead of peer + dev dependencies.

**Pull request merged**
