### PR TITLE
Add optional chaining checking for sheet.

### PR DESCRIPTION
**Pull request by lenient**
This may cause a blank page while navigating.

## Todo

- [ ] Add test(s) that verify the modified behavior
- [ ] Add documentation if it changes public API

### CODE REVIEW

**Comment by kof** [comment]
Hi
1. There must be a reason why you don't have a sheet in some case, so we need to figure out the reason and fix it, what you fixed is a consequence
2.  We need a test that reproduces the problem. Without a test I won't be able to merge

**Comment by lenient** [comment]
Hi @kof ,
This happens when using micro-frontend, I don't have a standalone example to reproduce it. But this happens on my local env, and `?.` is the way to fix it.

**Comment by kof** [comment]
You need to remove one dependency after another until its just jss

**Comment by kof** [comment]
please reopen once you have time

**Pull request closed without merging**
