### PR TITLE
[docs] Update SSR setup with react-jss

### PR DESCRIPTION
**Pull request by HenriBeck**
__What would you like to add/fix?__
This fixes resetting the `generateId` for SSR in v10.
This was reported in gitter.

### CODE REVIEW

**Comment by kof** [comment]
Looks good, but without a test I don't know what we are fixing

**Comment by HenriBeck** [comment]
The problem is that we are not resetting the generateId when someone tries to do SSR.
Lucien PESLIER reported this on gitter.

**Comment by kof** [comment]
I get the description, a bug needs a test though, otherwise its gonna be broken again.

**Comment by HenriBeck** [comment]
Yeah, so I tested quite a bit now, and I wasn't able to fix the bug. I think we need to require the user to regenerate it on every request.

**Comment by kof** [comment]
Did we change any behaviour from 9 to 10 here?

**Comment by HenriBeck** [comment]
Yeah, the context. This is the problem.

**Comment by kof** [comment]
Not sure how.

**Comment by HenriBeck** [comment]
When you call `renderToString` with the same root node, the context is being persisted. This means you second `renderToString` will still have the same context as the first one. That's why the counter is increasing. 

Not sure if this is a bug or a feature because if you call `render` with the same root node, it updates the node instead of re-rendering it which makes sense in the browser.

**Comment by kof** [comment]
I think its just a thing we need to document. Its how the new context works.

**Comment by HenriBeck** [comment]
Yeah, that's why I now changed the docs in this pr

**Pull request merged**
