### PR TITLE
Add integrity hashes to yarn.lock

### PR DESCRIPTION
**Pull request by oliviertassinari**
Field was added in `yarn@1.1.0`.

See yarnpkg/yarn#5042 for more information.

---

https://github.com/mui-org/material-ui/pull/13055

### CODE REVIEW

**Comment by kof** [comment]
strange, I am using yarn 1.9.4, someone is using an old version, we need to make sure to enforce yarn version, otherwise it will be back and forth

**Comment by oliviertassinari** [comment]
I have rerun the CI with no luck. It seems to be consistently failing. Did you make the BrowserStack creds public? I can help.

**Comment by oliviertassinari** [comment]
I have never seen any back and forth on Material-UI side.

**Comment by HenriBeck** [comment]
Yeah, it's because we don't give forks access to private env variables.

**Comment by oliviertassinari** [comment]
Can you make them public?

**Comment by kof** [comment]
that would mean everyone can access browserstack

**Comment by kof** [comment]
those are supposed to be private

**Comment by kof** [comment]
published v10.0.0-alpha.6

**Comment by oliviertassinari** [comment]
Everybody can access Material-UI BrowserStack. How are the other projects solving the problem?

**Pull request merged**
