### PR TITLE
Replace global polyfill with globalThis

### PR DESCRIPTION
**Pull request by TrySound**
https://twitter.com/IAmTrySound/status/1147174216095211520

__What would you like to add/fix?__

__Corresponding issue (if exists):__

### CODE REVIEW

**Comment by kof** [comment]
some new errors here https://travis-ci.org/cssinjs/jss/builds/554779472#L721

**Comment by kof** [comment]
seems like it doesn't work on IE10, if so  I think this package wasn't ever widely used

**Comment by TrySound** [comment]
Yes, ie10 support is not provided. Why do you still support it?

**Comment by kof** [comment]
because react does too

**Comment by TrySound** [comment]
Not really. React requires polyfills
https://reactjs.org/docs/react-dom.html#browser-support

**Comment by kof** [comment]
we can ask to add polyfills too if that solves the problem

**Comment by kof** [comment]
we actually already do

**Pull request closed without merging**
