### PR TITLE
Require Node 4+ (fix #338)

### LINKED ISSUE #338: devDependencies do not work in Node 7
I wanted to send pull request but just increasing a version is not enough. devDependencies won’t install on Node 7 because of `codecov` which uses deprecated version of `graceful-fs` and this is the latest version of `codecov`.

```
❯ npm i
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

...

❯ npm ls graceful-fs
jss@5.5.5 /Users/tema/jss
...
├─┬ codecov@1.0.1
│ └─┬ execSync@1.0.2
│   └─┬ temp@0.5.1
│     └─┬ rimraf@2.1.4
│       └── graceful-fs@1.2.3
...
```

They have an issue for that since June: https://github.com/codecov/codecov-node/issues/19.

### PR DESCRIPTION
**Pull request by sapegin**
As discussed in https://github.com/cssinjs/jss/issues/338

### CODE REVIEW

**Comment by kof** [comment]
Can you please add the info about dev node requirement v. >= 5 < 7 ? 
Somewhere here
https://github.com/cssinjs/jss/blob/master/docs/setup.md#run-tests

**Comment by kof** [comment]
Same for other pr's.

**Comment by sapegin** [comment]
Can I move it to Contribution.md in the project root? Since it’s more common location and GitHub also shows a link when you create a PR.

**Comment by kof** [comment]
Good idea, yes!

**Comment by kof** [comment]
The whole running tests thing belong there as well I think

**Comment by kof** [comment]
would prefer lowercase contribution.md though

**Comment by kof** [comment]
And it should be probably linked in TOC in readme.md as a last point.

**Comment by sapegin** [comment]
Good enough for the first version?

**Comment by kof** [comment]
yep, nice, merged

**Comment by kof** [comment]
Just saw a good example https://github.com/pburtchaell/react-notification/blob/master/.github/CONTRIBUTING.md

**Pull request merged**
