### PR TITLE
JssProvider: convert class component to function component

### PR DESCRIPTION
**Pull request by behnammodi**
All local test passed
All flow check passed

https://github.com/cssinjs/jss/issues/1506

### CODE REVIEW

**Comment by kof** [comment]
I think we can merge it. I wouldn't merge the use "any" like that, but since we are migrating to typescript, these internal things won't be important anyways.

**Comment by behnammodi** [comment]
@kof Exactly, also currently we have a lot of `any` types, so we need a new PR to remove these.
so, please merge this

**Comment by behnammodi** [comment]
@kof Also, I didn't use `any` type in this PR

**Comment by kof** [comment]
sorry, I ment the other PR https://github.com/cssinjs/jss/pull/1508 but both of them seem ready, ideally a pair more eyes on them and we should release as a patch version I think both of them. If they cause problems we would have to revert quickly and release another patch version and then iterate.

**Comment by behnammodi** [comment]
> sorry, I ment the other PR #1508 but both of them seem ready, ideally a pair more eyes on them and we should release as a patch version I think both of them. If they cause problems we would have to revert quickly and release another patch version and then iterate.

Ok, also I tested both of them in a huge project everything is ok.

**Comment by behnammodi** [comment]
Please don't forget, we need to update this PR https://github.com/cssinjs/jss/pull/1508 from https://github.com/cssinjs/jss/pull/1507

**Review by hosseinmd — APPROVED** [review]
Looks good.
In the future, we could use `useContext(JssContext)` instead of `JssContext.Consumer`.

**Comment by kof** [comment]
merged 🎉

**Comment by kof** [comment]
Thank you!

**Comment by kof** [comment]
released in https://github.com/cssinjs/jss/releases/tag/v10.7.0

**Pull request merged**
