### PR TITLE
correct umd build fixes #1329

### LINKED ISSUE #1329: Including react-jss via systemjs; ReferenceError: module is not defined.
Hi! ✋

__Expected behavior:__
When connect library to the project via systemjs doesn't throw a reference error.

__Describe the bug:__
It happens because of two places in the code. If I wrap them into `try catch` - everything works great.

__dist/react-jss.js:line: 484__
```
module.exports = shouldUseNative() ? Object.assign : function (target, source) {
  	...
};
```
Pay attention on __shouldUseNative__ method (line: 484):
Снимок экрана 2020-04-12 в 18 17 33

and dist/react-jss.js:line:1180
```
{
    module.exports = require('./cjs/react-is.development.js');
}
```

__GitHub link:__ 
https://github.com/rocetspace/modules
`npm i && npm start` -> localhost:9000

__Versions (please complete the following information):__
 - jss: 10.1.1
- react-jss: 10.1.1
 - Browser [e.g. chrome, safari]: all browsers
 - OS [e.g. Windows, macOS]: all OS
Feel free to add any additional versions which you may think are relevant to the bug.

Снимок экрана 2020-04-12 в 15 14 31

### PR DESCRIPTION
**Pull request by sscaff1**
## Corresponding issue (if exists):
#1329 

## What would you like to add/fix?
The umd build wasn't an actual umd build. It failed to run in the context of an Microfrontend project (i.e. systemJS) or in the browser. This PR fixes that.

## Todo

- [ ] Add tests if possible
- [ ] Add changelog if users should know about the change
- [ ] Add documentation

### CODE REVIEW

**Comment by kof** [comment]
@TrySound wdyt?

**Comment by TrySound** [comment]
There are two changes in current pr
1. convert all node_modules from commonjs to es modules
2. import commonjs versions of babel helpers which has to be also converted to es modules

The second case is rather pointless and does not solve anything.
The first case solves the issue with untranspiled "object-assign" package a dependency of prop-types.

**Comment by kof** [comment]
@sscaff1 do you mind updating the PR according to @TrySound's feedback?

**Comment by kof** [comment]
please reopen, not sure what to do here

**Pull request closed without merging**
