### PR TITLE
[react-jss] TypeScript: Added support for innerRef prop

### PR DESCRIPTION
**Pull request by sorteam**
## Corresponding issue (if exists):
Can't pass innerRef prop

## What would you like to add/fix?
Add support for innerRef in types

## Todo

- [x] Add tests if possible
- [x] Add changelog if users should know about the change
- [x] Add documentation

### CODE REVIEW

**Comment by vismu** [comment]
Yep, actually, your last commit do right change, because `innerRef` prop is added only to HOC component. 
I will have one request.
Pls, add check of ability to pass `innerRef` prop to component `TestComponentWitStyles` at `index.test.tsx` file.

**Comment by sorteam** [comment]
@moshest check this please..

**Comment by moshest** [comment]
Can we have the tests use a real world example instead of `any`?

**Comment by kof** [comment]
merged

**Pull request merged**
