### PR TITLE
Use memoize-one package

### PR DESCRIPTION
**Pull request by timsnadden**
## Corresponding issue (if exists):
#1127
## What would you like to add/fix?
Use memoize-one package instead of custom implementation

### CODE REVIEW

**Comment by kof** [comment]
I appreciate the care, but I don't care enough about this to merge this compared to the risk breaking something and having another dependency. I can change my mind once there is a strong reason.

**Comment by timsnadden** [comment]
No worries. I was just looking through issues and saw it as a simple task
and thought I could do it to help out. Might as well close the issue though
eh?

**Comment by kof** [comment]
I am keeping them so that people don't create new once)

**Comment by kof** [comment]
If you want something to work on, I am happy to find you high prio issues

**Comment by timsnadden** [comment]
Cheers. Please do

**Comment by kof** [comment]
For example
https://github.com/cssinjs/jss/issues/1327
https://github.com/cssinjs/jss/issues/1288
https://github.com/cssinjs/jss/issues/1335

**Comment by kof** [comment]
I created this https://github.com/cssinjs/jss/issues/1359, let's see if its a good idea

**Pull request closed without merging**
