### PR TITLE
Add ES Modules support

### PR DESCRIPTION
**Pull request by HenriBeck**
- Added compiling to ES Modules with babel
- Upgraded to babel 7

Some babel 6 packages are still needed because of babel-plugin-rewire, once we moved the tests to jest we can use jest mocking functionality and remove babel-plugin-rewire

### CODE REVIEW

**Comment by kof** [comment]
wait @TrySound was already working on esm build for the dist

**Comment by TrySound** [comment]
Yes, I want to provide do a bundles instead. I can send a pr this evening.

**Comment by HenriBeck** [comment]
Are there any advantages over a flat bundle? I assume you can load it in the browser as well, right?

**Comment by TrySound** [comment]
A bunch of
- more controllable size and output
- slightly faster bundling
- faster browser loading if somebody will use it
- better debugging in development mode without sourcemaps (less webpack stuff)
- hidden internals which may cause breaking changes if user decide to use them

**Comment by HenriBeck** [comment]
Okay, sounds great. 👍

**Pull request closed without merging**
