### PR TITLE
Updated css-vendor to 2.0.7

### PR DESCRIPTION
**Pull request by AleshaOleg**
__What would you like to add/fix?__

Updated `css-vendor` to `2.0.7`.

__Corresponding issue (if exists):__

https://github.com/cssinjs/jss/issues/1204

### CODE REVIEW

**Comment by kof** [comment]
pls add a changelog

**Comment by AleshaOleg** [comment]
@kof which version will be next? `10.0.1`? Because I can't even find changelog for `10.0.0`

**Comment by kof** [comment]
You don't need to define the next version, here is an example of how changelog looks like before a version is released: https://github.com/cssinjs/jss/blob/0934862f1340ae983e78c921419b386f6f9d0d92/changelog.md

**Comment by AleshaOleg** [comment]
@kof

**Comment by kof** [comment]
merged, thanks @AleshaOleg , sorry for waiting

**Pull request merged**
