### PR TITLE
feat(units): add `gap`

### LINKED ISSUE #1348: CSS Property `gap` not receiving a default unit
__Expected behavior:__
- CSS Property `gap` would receive a default unit of `px` for example
- Stretch goal, add `grid-gap` to maintain compatibility

__Describe the bug:__
A clear and concise description of what happened instead of the expected behavior.
- CSS Property `gap` not receiving a default unit, but is just a number making it invalid css

__Codesandbox link:__ 
Please create a [codesandbox.io](https://codesandbox.io/) with the issue. Make it as minimal as possible as this will help us find the bug quicker.
https://codesandbox.io/s/muddy-lake-h4k93?file=/src/App.tsx
`gridGap` is commented out to show the difference

__Versions (please complete the following information):__
 - jss: 10.1.1
 - Browser [e.g. chrome, safari]: chrome 81
 - OS [e.g. Windows, macOS]: mac

According to MDN, `grid-gap` is now being replaced with just `gap` in order to get ready for full support of `gap` for `flexbox`: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
However, they also suggest that both properties be used in the mean time. 

For context, I made this issue originally in [Material-UI](https://github.com/mui-org/material-ui/issues/21235) and was directed this direction

I'm not sure where we would add code? A default value needs to be added to [jss-plugin-default-unit](https://github.com/cssinjs/jss/blob/d9cca31ad2d058aa0108fa6ec48fe872b0e7e886/packages/jss-plugin-default-unit/src/defaultUnits.js#L126), but for compatibility, where could we add a `grid-gap` property for every `gap` used? It isn't a vendor prefix, but css-vendor would tell if it was needed.

If I could be pointed in the right direction, I'd love to do a PR for this.
Thanks!

### PR DESCRIPTION
**Pull request by moshfeu**
## Corresponding issue (if exists):

resolve #1348

## What would you like to add/fix?

Add gap to defaultUnits

## Todo

- [ ] Add tests if possible
- [ ] Add changelog if users should know about the change
- [ ] Add documentation

### CODE REVIEW

**Comment by kof** [comment]
I would place it right after grid-gap, since the later was deprecated, also not sure if we still need to support grid-gap

**Comment by moshfeu** [comment]
I wasn't sure because it also affect on `flex`, let me know.

**Comment by kof** [comment]
merged, thanks

**Comment by kof** [comment]
https://github.com/cssinjs/jss/releases/tag/v10.5.0

**Pull request merged**
