### PR TITLE
Fixed data param

### PR DESCRIPTION
**Pull request by wellguimaraes**

### CODE REVIEW

**Comment by kof** [comment]
Thanks, weird nobody noticed, will add a test.

**Comment by kof** [comment]
I was too fast, if you read exactly there is arguments overload.I wonder why you tried to fix it if nothing is broken.

**Comment by wellguimaraes** [comment]
Hey @kof , thank you for the quick reply. Well, sorry for that, but I'm facing this issue:

- When there's some conditional rule (ex.: media query), the properties defined with functions are called sometimes with undefined param.

I'll investigate it better then.

**Comment by kof** [comment]
please create a failing test or at least a proper example of whats failing

**Comment by wellguimaraes** [comment]
Sure, I'll do.
;)

**Comment by wellguimaraes** [comment]
I had this problem while using styled-jss and I've just found the issue in that project. Sorry for the mess @kof ! ;)

**Pull request merged**
