### PR TITLE
Move getDynamicStyles into react-jss package

### PR DESCRIPTION
**Pull request by kof**
Just moving a function.

### CODE REVIEW

**Comment by Vadorequest** [comment]
@kof This broke our builds. https://github.com/mui-org/material-ui/issues/20132

Could a revert be made ASAP until a proper way of fixing this is found?

**Comment by Vadorequest** [comment]
I believe this supposedly private function was actually used by other libraries, such as material-ui. This becomes a breaking change and should be done using a major release change.

**Comment by kof** [comment]
Should be fixed now  in 10.1.1

**Comment by Vadorequest** [comment]
Just confirming it works again. Thank you for the quick fix!

**Pull request merged**
