### PR TITLE
Fix createGenerateClassName docs

### PR DESCRIPTION
**Pull request by sapegin**
I may miss something but that’s the only way it works for me.

### CODE REVIEW

**Comment by kof** [comment]
why? both is valid

**Comment by kof** [comment]
But yeah maybe it is more clear to use setup?

**Comment by sapegin** [comment]
For some reason `create` didn’t work. Maybe I did something wrong. But the first commit should be right anyway ;-)

**Comment by kof** [comment]
did you do a setup after create? if so it overrides … mb I need to allow multiple .setup calls to extend each other.

**Comment by sapegin** [comment]
Yeah, I did. And it’s surprising behavior ;-)

**Comment by kof** [comment]
I was thinking create(options) is same like create().setup(options) ... so one would use one of them, but yeah ...

**Comment by sapegin** [comment]
Is there any technical requirement to overwrite previous options?

**Comment by kof** [comment]
No, but thats what you expected, right?

**Comment by sapegin** [comment]
I’m not 100% sure, worth a poll ;-) Maybe docs should be clearer that setup and create is almost the same thing.

**Comment by kof** [comment]
Well create creates an instance, setup sets up an existing instance. They are not the same, but create is using setup

**Comment by sapegin** [comment]
Also `use` doesn’t overwrite settings and looks like it’s not documented on this page ;-)

**Comment by kof** [comment]
Maybe we just need an info that create is calling setup and that setup redefines a setup.

**Comment by sapegin** [comment]
Yeah, would be nice. I’ll try to add.

**Comment by kof** [comment]
use is always adding a plugin, yes it is basically extending, but use is also designed for subsequent calls ...

**Comment by sapegin** [comment]
Also I don’t understand this part:

> Note: in production it uses just the "c" + rules counter.

How to enable production mode?

**Comment by kof** [comment]
NODE_ENV=production ... yeah lets add this too.

**Comment by sapegin** [comment]
Seems not to work for me. (Even before I’ve added custom names.)

**Comment by sapegin** [comment]
Or is it 9.x specific?

**Comment by kof** [comment]
yes it is a new feature, exists only in next releases

**Comment by sapegin** [comment]
Will it affect custom names?

**Comment by kof** [comment]
nope, if user has own class name generation function, they will have to do the same in order to support it.

**Pull request merged**
