### PR TITLE
Fixed some Flow annotations

### LINKED ISSUE #484: Wrong flow type args?
Regarding this line:
https://github.com/cssinjs/jss/blob/master/src/Jss.js#L47

Should it be this instead?:

```js
  createStyleSheet(styles: Object, options?: StyleSheetOptions): StyleSheet {
```

### PR DESCRIPTION
**Pull request by ffxsam**
Fixes #484

### CODE REVIEW

**Comment by kof** [comment]
thanks, merged

**Comment by kof** [comment]
Oh, you didn't run flow on it, now ci is broken.

**Comment by ffxsam** [comment]
Ugh. hang on..

**Comment by ffxsam** [comment]
Maybe revert to commit `4081712` for now on master. Sorry about that! There's a lot more fixing up that has to happen here.

**Pull request merged**
