### PR TITLE
add tiny-warning to deps

### PR DESCRIPTION
**Pull request by dgreuel**
## Todo

- [ ] Add tests if possible
- [ ] Add changelog if users should know about the change
- [ ] Add documentation

### CODE REVIEW

**Comment by kof** [comment]
did you add it with yarn add? lock file isn't updated

**Comment by dgreuel** [comment]
> did you add it with yarn add? lock file isn't updated

Yes, did `yarn add tiny-warning@^1.0.2`. The entry is already in the lockfile

**Comment by kof** [comment]
merged, thanks!

**Comment by mciparelli** [comment]
packages like `@material-ui/`styles depend on `jss-plugin-rule-value-function` directly, which hasn't been bumped yet. Could you release a new version of `jss-plugin-rule-value-function` that contains `tiny-warning` dependency?

**Comment by gamb** [comment]
@kof I can put up a release PR if helpful? As @mciparelli mentions ☝️

**Comment by aashish1999-cypher** [comment]
Is the issue solved my project is stuck??

**Comment by kof** [comment]
Released in v10.2.0

**Pull request merged**
