### PR TITLE
Keep classes ref when sheet and dynamicRules have not any change

### PR DESCRIPTION
**Pull request by behnammodi**
## What Would You Like to Add/Fix?
`getSheetClasses` always return new object even `sheet` and `dynamicRules` haven't any change

Also I wrote a small test to keep it in future

## Todo

- [x] Add test(s) that verify the modified behavior

## Expectations on Changes
So, I memoized it to prevent this behavior

## Changelog
Improve performance at `useStyle`

### CODE REVIEW

**Comment by behnammodi** [comment]
@kof This is ready to merge

**Comment by kof** [comment]
@behnammodi thanks, will look into it, in the meantime, please test it in your app in production and let me know if you notice anything

**Comment by behnammodi** [comment]
> @behnammodi thanks, will look into it, in the meantime, please test it in your app in production and let me know if you notice anything

Sure, I'll tell you

**Comment by behnammodi** [comment]
@kof I build `react-jss` then create a `pack` and install on our project everything works very well

**Comment by behnammodi** [comment]
@kof I found a better solution, please see this file `packages/react-jss/src/createUseStyles.js` changes

**Comment by behnammodi** [comment]
@kof This PR ready to merge and main change is:

```diff
-    const classes = sheet && dynamicRules ? getSheetClasses(sheet, dynamicRules) : emptyObject
+    const classes = React.useMemo(
+      () => (sheet && dynamicRules ? getSheetClasses(sheet, dynamicRules) : emptyObject),
+      [sheet, dynamicRules]
+    )
```

**Comment by kof** [comment]
looks great now, thank you

**Comment by kof** [comment]
released in v10.9.0

**Pull request merged**
