### PR TITLE
Use Phantom for PR builds

### PR DESCRIPTION
**Pull request by Graham42**
This might fix PR builds. Opening the PR to trigger build to find out.

### CODE REVIEW

**Comment by kof** [comment]
what about core maintainers pull requests?

**Comment by Graham42** [comment]
Going to have to give this more thought

**Comment by iamstarkov** [comment]
I would recommend puppeteer for more reliable tests

**Comment by kof** [comment]
Ideally would be to still run tests in all browsers like we normally do.

**Pull request closed without merging**
