### PR TITLE
Generate cjs and umd flat bundles

### PR DESCRIPTION
**Pull request by TrySound**
A few reasons to bundle

- more controllable size and output
- slightly faster bundling
- faster browser loading if somebody will use it
- better debugging in development mode without sourcemaps (less webpack stuff)
- hidden internals which may cause breaking changes if user decide to use them

### CODE REVIEW

**Comment by kof** [comment]
> Guys, let's use squash and merge button. It provides less noise in commit history.

I am for it, usually I simply forget to press it lol

**Comment by TrySound** [comment]
Me too. There should be an option in project settings to restrict with only that button. Could you try it?

**Comment by kof** [comment]
Cool, didn't know it was an option, just activated it

**Comment by HenriBeck** [comment]
Looks good👍

What is the code property inside the size snapshot files? And why is there a difference between rollup and webpack?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TrySound** [comment]
`code` is the size of treeshaked and minified code
`import_statements` is the size of import statements in the code
So when both this values are equal we have perfect treeshakability. Import statements just considered as side effectful and not treeshaked.

Webpack is different because its treeshaking abilities are less perfect than rollup ones + webpack adds runtime and doesn't have esm output.

**Pull request merged**
