### PR TITLE
Selector escaping 

### LINKED ISSUE #557: Linker doesn't work with escaped selectors
Linker is the  function that references the css rule object as a `renderable` property on the StyleRule instance.

I think it breaks when selector contains escaped characters.

https://www.webpackbin.com/bins/-KqgiTDVbilzhS2C8xaD

### PR DESCRIPTION
**Pull request by kof**
Fixes #557

### CODE REVIEW

**Comment by iamstarkov** [comment]
@kof i would delete future merged branches, if you dont mind

**Comment by iamstarkov** [comment]
btw, pls publish beta releases by `@next` dist tag

**Comment by iamstarkov** [comment]
so people wont be confused by experimental release

**Comment by kof** [comment]
you mean I deleted branches which haven't been merged?

**Comment by kof** [comment]
never used npm tags, why is it important to use next tag?

**Comment by kof** [comment]
version has pre suffix, isn't it enough?

**Pull request merged**
