### PR TITLE
Warn when using a wrong at-rule

### PR DESCRIPTION
**Pull request by oliviertassinari**
This warning is improving the user feedback when not using the API correctly.

> TypeError: AtRule is not a constructor

I just had the above issue with an incorrect `@raw` rule.

### CODE REVIEW

**Comment by nathanmarks** [comment]
Nice 👍 Just a couple of lint errors to fix up

**Comment by kof** [comment]
What did you use that is not supported?

**Comment by oliviertassinari** [comment]
@nathanmarks Sure, should we had a unit test too?
@kof I was migrating from another CSS-in-JS engine (stylishly)

**Comment by kof** [comment]
Yeah, ideally we need a test, linted and a better message: `warning(AtRule, '[JSS]: unknown rule %s', name)`

**Comment by oliviertassinari** [comment]
> Yeah, ideally we need a test

We would probably need to stub `console`. I know @nathanmarks isn't keen on this idea.
That would also throw an error. We will need to add a try / catch block.

**Comment by kof** [comment]
Just realized: it shouldn't be a warning, it should be a thrown Error. Something like this is not just a hint, it won't work and we have no fallback to something that could work. And this should be fixable during development and should not happen in production.

**Comment by kof** [comment]
If we use a warning, we need to implement some fallback, which is probably a regular Rule instance. As it is now, the next line after warning it will throw because we still have no AtRule ...

**Comment by oliviertassinari** [comment]
Right. I'm not sure what's the best approach is.
Do you want to have a fallback?
Or should we throw with a better error message than `TypeError: AtRule is not a constructor`.

**Comment by kof** [comment]
Wether we need a fallback or not depends on: can this error happen in production or will this always be visible during development. If the last one  - then throw, if first one - warning and fallback.

**Comment by kof** [comment]
I think your case is something that can happen only in development, right?

**Comment by oliviertassinari** [comment]
For my use case, a throw would be better. For others, I don't know. What if someone is generating the rule with a variable and he mess something around?

**Comment by kof** [comment]
Well this is not entirely impossible, but I can hardly imagine that in this particular case.

**Comment by oliviertassinari** [comment]
let's throw then, it's gonna make the test implementation simpler 👍 . Thanks.

**Comment by kof** [comment]
On the other hand, CSS never throws into jss so that the program can break. Maybe its a good general rule to stick to, no matter if it makes sense in some particular case or not. Just always render something even if it is wrong. A visual bug is better than a program that stopped working completely.

**Comment by oliviertassinari** [comment]
> A visual bug is better than a program that stopped working completely

Put it that way, I can't agree more.

**Comment by kof** [comment]
Then we need a warning and a fallback with a Rule instance.

**Comment by oliviertassinari** [comment]
I have forgotten this PR. Any update?

**Comment by kof** [comment]
thats basically fine, I will make some changes afterwards.

**Comment by kof** [comment]
merged, thanks!

**Pull request merged**
