### PR TITLE
Support array functions from function values + !important

### PR DESCRIPTION
**Pull request by kof**
Original PR https://github.com/cssinjs/jss/pull/631

### CODE REVIEW

**Comment by kof** [comment]
@simplersoftware please check this pr also, for some reason your commits don't link to your github account

**Comment by SimplerSoftware** [comment]
@kof , lgtm.  Thanks for all your hard work on this project!

**Comment by kof** [comment]
Thank you for your help, consider helping more if you are interested!

**Comment by SimplerSoftware** [comment]
@kof Are you going to be able to release a new NPM package for 9.4.0 in the near future?

**Comment by kof** [comment]
definitely

**Pull request merged**
