### PR TITLE
Use files field in package.json instead of .npmignore

### PR DESCRIPTION
**Pull request by sapegin**
That’s what you publish to npm now:

image 2017-02-03 at 7 32 54 pm

Most of this files aren‘t necessary. I’m not sure about flow files though.

### CODE REVIEW

**Comment by kof** [comment]
I am not sure what to do with docs.
flow-typed needs to be in the package right now

**Comment by kof** [comment]
also changelog is nice to have in the package

**Comment by kof** [comment]
and license

**Comment by kof** [comment]
and readme)))

**Comment by sapegin** [comment]
`flow-typed` or `.flowconfig` or both? 

I never publish docs but some people do. So it‘s up to you ;-)

Readme, changelog and License should be added automatically: https://docs.npmjs.com/files/package.json#files

**Comment by kof** [comment]
Are there any reasoning about what to include and what not to? I found it useful to be able to read quickly the docs right from node_modules. But maybe there is a general consensus to only include code?

**Comment by sapegin** [comment]
I don’t know about that. But thing like tests, linter configs, etc. shouldn’t bloat `node_modules` ;-)

**Comment by sapegin** [comment]
I’ve heard from someone that they read docs in `node_modules` while they are offline ;-)

**Comment by kof** [comment]
Maybe, sometimes tests are saying more than docs …

**Comment by kof** [comment]
I totally agree regarding everything dev related, not sure about tests though…

**Comment by kof** [comment]
Ok so lets clarify what needs to be included for webpack 2, otherwise readme.md, license, changelog, flow-typed, dist, lib should be included I think.

**Comment by sapegin** [comment]
As I understand you need to use `module` field in package.json, it should point to ES6 version of your code. You can’t use anything ES6+ here (you’ll have to transpile) and `import`s should be there.

**Comment by sapegin** [comment]
http://survivejs.com/webpack/advanced-techniques/authoring-packages/#understanding-package-json-

**Comment by sapegin** [comment]
I’ve added `flow-typed`. Readme.md, license, changelog are defaults. Webpack 2 probably needs some experimentation.

**Comment by sapegin** [comment]
Looks like I was wrong: you need to transpile as usual except ES6 modules: https://github.com/survivejs/webpack-book/blob/dev/manuscript/advanced_techniques/02_authoring_packages.md#what-files-to-publish-to-npm

**Comment by kof** [comment]
Yeah, sounds right. So we are actually done here, right?

**Comment by kof** [comment]
Ah no, module field…

**Comment by sapegin** [comment]
I think `module` field would be out of scope of this PR, because it’d require extra Babel configuration.

**Comment by kof** [comment]
ok

**Comment by kof** [comment]
merged, thanks!

**Comment by sapegin** [comment]
Cool, could you do the same for other JSS projects? Or we can setup mrm for that ;-)

**Comment by kof** [comment]
Yes, exactly my plan, need to try mrm for that and lots of other things. Though maybe I will need a separate repository for that common stuff for "plugins", because they are a bit different than the core.

**Comment by sapegin** [comment]
Most probably. Have you seen [webpack-defaults](https://github.com/webpack-contrib/webpack-defaults)?

**Comment by kof** [comment]
nope, sounds like a good place to learn from, most probably would need to change a lot, but could use it as a starting point, right?

**Comment by sapegin** [comment]
Yeah, sure. It’s not integrated into any project yet. Let me know if you need any help ;-)

**Pull request merged**
